//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemcasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIHAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIHAT()
        {
            this.THUCHIENs = new HashSet<THUCHIEN>();
        }
    
        public string MABAIHAT { get; set; }
        public string TENBAIHAT { get; set; }
        public string GIAIDIEU { get; set; }
        public string MATHELOAI { get; set; }
        public string MANHACSY { get; set; }
        public string GHICHU { get; set; }
    
        public virtual NHACSY NHACSY { get; set; }
        public virtual THELOAI THELOAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCHIEN> THUCHIENs { get; set; }
    }
}
