//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemcasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANNHAC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BANNHAC()
        {
            this.NHACCONGs = new HashSet<NHACCONG>();
            this.THUCHIENs = new HashSet<THUCHIEN>();
        }
    
        public string MABANNHAC { get; set; }
        public string TENBANNHAC { get; set; }
        public string SODTLIENHE { get; set; }
        public string MATRUONGNHOM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHACCONG> NHACCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCHIEN> THUCHIENs { get; set; }
    }
}
