//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemcasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASY()
        {
            this.THUCHIENs = new HashSet<THUCHIEN>();
        }
    
        public string MACASY { get; set; }
        public string TENCASY { get; set; }
        public string DIACHI { get; set; }
        public string SODIENTHOAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCHIEN> THUCHIENs { get; set; }
    }
}
