//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemcasy
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACCONG
    {
        public string MANHACCONG { get; set; }
        public string TENNHACCONG { get; set; }
        public string NHACCUSUDUNG { get; set; }
        public string MABANNHAC { get; set; }
    
        public virtual BANNHAC BANNHAC { get; set; }
    }
}
